<script lang="ts">
  import '$lib/components/destinations/destination.css';
  import { ArrowDown, ArrowUpRight, ArrowRight, ChevronRight, MapPin, Compass } from '@lucide/svelte';
  import { Button } from '$lib/components/ui/button';
  import * as Accordion from '$lib/components/ui/accordion';
  import SiteHeader from '$lib/components/home/site-header.svelte';
  import SiteFooter from '$lib/components/home/site-footer.svelte';
  import Enquiry from '$lib/components/home/enquiry.svelte';
  import DestinationImage from '$lib/components/destinations/destination-image.svelte';
  import DestinationGuide from '$lib/components/destinations/destination-guide.svelte';
  import RichText from '$lib/components/tours/rich-text.svelte';
  import TourCard from '$lib/components/tours/tour-card.svelte';
  import StayCard from '$lib/components/stays/stay-card.svelte';
  import { destinationGuide, destinationImage, destinationHref, destinationFallbackPhoto } from '$lib/destination-content';
  import { safeUrl, textContent } from '$lib/home-content';
  import { siteInfo } from '$lib/site-info';
  import { planHref } from '$lib/planner/plan-href';
  import type { PageProps } from './$types';
  let {data,form}:PageProps=$props();
  let d=$derived(data.destination), chrome=$derived(data.chrome);
  let interest=$state('');
  const chooseInterest=(name:string)=>{interest=name;};
  let enquiry=$derived(chrome.sections.find(s=>s.section_key==='enquiry'&&s.is_active!==false));
  let blocks=$derived(destinationGuide(d.guide));
  let embeddedQuestions=$derived(new Set(blocks.filter(b=>b.type==='faq').flatMap(b=>b.items.map(i=>i.title.trim().toLowerCase()))));
  let faqs=$derived(data.faqs.filter(f=>!embeddedQuestions.has(f.question.trim().toLowerCase())));
  let safety=$derived([{title:'Safety overview',body:d.safety_overview},{title:'Health & vaccinations',body:d.health_vaccinations},{title:'Security advice',body:d.security_advice},{title:'Travel insurance',body:d.travel_insurance_note},{title:'Emergency contacts',body:d.emergency_contacts}].filter(s=>s.body?.trim()));
  let scores=$derived([{title:'Wildlife',value:d.score_wildlife},{title:'Comfort & luxury',value:d.score_luxury},{title:'Family travel',value:d.score_family},{title:'Photography',value:d.score_photography},{title:'Adventure',value:d.score_adventure}].filter(s=>s.value!==null&&s.value!==undefined&&Number.isFinite(Number(s.value))));
  let hero=$derived(destinationImage(d,true));
  let title=$derived(d.meta_title||`${d.name} | ${siteInfo.brand}`);
  let description=$derived(textContent(d.meta_description||d.short_description||d.description).slice(0,170));
  let canonical=$derived(data.siteOrigin+destinationHref(d));
  let nav=$derived([{id:'overview',label:'Overview'},...(blocks.length?[{id:'destination-guide',label:'Destination guide'}]:[]),...(data.activities.length?[{id:'experiences',label:'Experiences'}]:[]),...(data.tours.length?[{id:'destination-tours',label:'Safaris'}]:[]),...(data.stays.length?[{id:'destination-stays',label:'Where to stay'}]:[]),...(safety.length?[{id:'travel-essentials',label:'Travel essentials'}]:[]),...(faqs.length?[{id:'destination-faqs',label:'FAQs'}]:[])]);
  let onPage=$derived(['top',...nav.map(n=>n.id),...(enquiry?['request-quote']:[])]);
  let mapUrl=$derived(typeof d.latitude==='number'&&typeof d.longitude==='number'&&Number.isFinite(d.latitude)&&Number.isFinite(d.longitude)&&Math.abs(d.latitude)<=90&&Math.abs(d.longitude)<=180?`https://www.google.com/maps/search/?api=1&query=${d.latitude},${d.longitude}`:'');
  let schema=$derived(JSON.stringify({'@context':'https://schema.org','@graph':[{'@type':'TouristDestination',name:d.name,description,url:canonical,...(hero?{image:new URL(hero,data.siteOrigin).href}:{})},{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:data.siteOrigin},{'@type':'ListItem',position:2,name:'Destinations',item:data.siteOrigin+'/destinations'},{'@type':'ListItem',position:3,name:d.name,item:canonical}]}]}).replace(/</g,'\\u003c'));
</script>
<svelte:head><title>{title}</title><meta name="description" content={description}/><link rel="canonical" href={canonical}/><meta property="og:title" content={title}/><meta property="og:description" content={description}/><meta property="og:url" content={canonical}/><meta property="og:type" content="website"/><meta property="og:site_name" content={siteInfo.company}/>{#if safeUrl(d.og_image_url,'')||hero}<meta property="og:image" content={new URL(safeUrl(d.og_image_url,'')||hero,data.siteOrigin).href}/>{/if}<meta name="twitter:card" content="summary_large_image"/>{@html `<script type="application/ld+json">${schema}</script>`}</svelte:head>
<a href="#main" class="sr-only focus:not-sr-only">Skip to content</a>
<SiteHeader visible={chrome.visible} activities={chrome.activities} destinations={chrome.destinations} tours={chrome.navTours} stays={chrome.navStays} categories={chrome.categories} onInterest={chooseInterest} {onPage}/>
<main id="main">
  <section class="destination-hero" id="top"><DestinationImage urls={[hero,d.main_image_url,d.image_url]} alt={d.name} fallback={destinationFallbackPhoto(d)||'/images/tanzania-hero-2.jpg'} hero/><div class="destination-hero-inner page-container"><nav class="destination-breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a><ChevronRight size={12}/><a href="/destinations">Destinations</a><ChevronRight size={12}/><span aria-current="page">{d.name}</span></nav><div class="destination-hero-main"><div class="destination-hero-copy"><p class="eyebrow">{[d.country,d.region].filter(Boolean).join(' / ')||'A PLACE WORTH THE JOURNEY'}</p><h1>{d.name}</h1>{#if d.short_description}<p class="destination-hero-description">{textContent(d.short_description)}</p>{/if}<div class="destination-hero-actions"><Button href="#overview" variant="safari">Discover {d.name}<ArrowDown size={16}/></Button>{#if enquiry}<Button href={planHref({destination:d.slug,from:'destination_page'})} data-cta="plan_my_trip" data-cta-location="destination_page" variant="outline" class="border-white/60 bg-transparent text-white hover:bg-white/10 hover:text-white">Plan a visit <ArrowUpRight size={16}/></Button>{/if}</div></div></div></div></section>
  <nav class="destination-section-nav" aria-label="On this destination page"><div class="page-container">{#each nav as item}<a href={`#${item.id}`}>{item.label}</a>{/each}</div></nav>
  <div class="page-container destination-editorial destination-section">
    <div class="destination-story">
      <section id="overview"><p class="eyebrow text-muted-foreground">GET TO KNOW {d.name.toUpperCase()}</p><h2 class="section-heading mt-4 mb-6">A place with its own story.</h2><RichText value={d.description||d.short_description}/></section>
      {#if blocks.length}<div id="destination-guide"><DestinationGuide {blocks}/></div>{/if}
    </div>
    <aside class="destination-aside"><div class="destination-planner"><Compass size={27}/><p class="eyebrow">YOUR DESTINATION, AT A GLANCE</p><h2>{d.name}</h2><p class="location-line"><MapPin size={15}/>{[d.location,d.region,d.country].filter((v,i,a)=>v&&a.indexOf(v)===i).join(' · ')}</p>{#if scores.length}<div class="destination-scores"><p>Our destination ratings</p>{#each scores as score}<div><span>{score.title}</span><span>{score.value}/10</span><meter min="0" max="10" value={Number(score.value)} aria-label={`${score.title}: ${score.value} out of 10`}></meter></div>{/each}</div>{/if}{#if mapUrl}<a class="map-link" href={mapUrl} target="_blank" rel="noopener noreferrer">See the location <ArrowUpRight size={15}/></a>{/if}{#if enquiry}<Button href={planHref({destination:d.slug,from:'destination_page'})} data-cta="plan_my_trip" data-cta-location="destination_page" variant="safari" class="mt-6 w-full whitespace-normal">Include in my journey <ArrowRight size={16}/></Button>{/if}<a class="all-places" href="/destinations">Explore all destinations</a></div></aside>
  </div>
  {#if data.activities.length}<section id="experiences" class="destination-section mist"><div class="page-container"><div class="destination-section-head"><div><p class="eyebrow">GO BEYOND THE VIEW</p><h2 class="section-heading">Experience {d.name}.</h2></div></div><div class="destination-grid">{#each data.activities as activity}<article class="destination-activity">{#if safeUrl(activity.hero_image_url||activity.image_url,'')}<div class="activity-photo"><DestinationImage urls={[activity.hero_image_url,activity.image_url]} alt={activity.name}/></div>{/if}<div><h3>{activity.name}</h3><p>{textContent(activity.description)}</p>{#if enquiry}<Button href={planHref({destination:d.slug,activity:activity.slug,from:'destination_page'})} data-cta="plan_my_trip" data-cta-location="destination_page" variant="outline">Add to my journey <ArrowUpRight size={15}/></Button>{/if}</div></article>{/each}</div></div></section>{/if}
  {#if data.tours.length}<section id="destination-tours" class="destination-section page-container"><div class="destination-section-head"><div><p class="eyebrow">MAKE IT A JOURNEY</p><h2 class="section-heading">Safaris that take you here.</h2></div><Button href={`/tours?destination_id=${encodeURIComponent(d.id)}#tour-results`} variant="outline">All {data.tourTotal} safaris <ArrowUpRight size={16}/></Button></div><div class="destination-grid">{#each data.tours as tour}<TourCard {tour}/>{/each}</div></section>{/if}
  {#if data.stays.length}<section id="destination-stays" class="destination-section mist"><div class="page-container"><div class="destination-section-head"><div><p class="eyebrow">WAKE UP SOMEWHERE SPECIAL</p><h2 class="section-heading">Stay a little closer.</h2></div><Button href={`/stays?destination_id=${encodeURIComponent(d.id)}#stay-results`} variant="outline">All {data.stayTotal} stays <ArrowUpRight size={16}/></Button></div><div class="destination-grid">{#each data.stays as stay}<StayCard {stay} destination={d}/>{/each}</div></div></section>{/if}
  {#if safety.length||faqs.length}<div class="page-container destination-section detail-questions">{#if safety.length}<section id="travel-essentials"><p class="eyebrow text-muted-foreground">BEFORE YOU GO</p><h2 class="section-heading mt-4 mb-6">Travel essentials.</h2><Accordion.Root type="multiple">{#each safety as item,i}<Accordion.Item value={String(i)}><Accordion.Trigger class="text-left">{item.title}</Accordion.Trigger><Accordion.Content><RichText value={item.body}/></Accordion.Content></Accordion.Item>{/each}</Accordion.Root></section>{/if}{#if faqs.length}<section id="destination-faqs"><p class="eyebrow text-muted-foreground">A LITTLE CLARITY</p><h2 class="section-heading mt-4 mb-6">Good to know.</h2><Accordion.Root type="multiple">{#each faqs as faq}<Accordion.Item value={faq.id}><Accordion.Trigger class="text-left">{faq.question}</Accordion.Trigger><Accordion.Content><RichText value={faq.answer}/></Accordion.Content></Accordion.Item>{/each}</Accordion.Root></section>{/if}</div>{/if}
  {#if data.relatedUnavailable}<p class="page-container pb-8 text-sm text-muted-foreground">Some trip options are temporarily unavailable. Our team can help you explore what fits your journey.</p>{/if}
  {#if enquiry}<section class="page-container py-12"><div class="destination-cta"><div><p class="eyebrow">LET’S MAKE IT PERSONAL</p><h2>Picture yourself in {d.name}.</h2><p>We’ll help choose the route, the pace and the places to stay. You bring the curiosity.</p></div><Button href={planHref({destination:d.slug,from:'destination_page'})} data-cta="plan_my_trip" data-cta-location="destination_page" variant="safari">Plan my journey <ArrowRight size={17}/></Button></div></section><Enquiry section={enquiry} {form} interest={interest||`A journey to ${d.name}`}/>{/if}
</main>
<SiteFooter visible={chrome.visible} destinations={chrome.destinations} onInterest={chooseInterest} {onPage}/>
<style>
.destination-section-nav{border-bottom:1px solid #e1e5e7;background:#faf9f4}.destination-section-nav>div{display:flex;gap:28px;overflow-x:auto}.destination-section-nav a{padding:22px 0;font-size:12px;font-weight:500;white-space:nowrap;color:#516779}.destination-section-nav a:hover{color:#14314d;text-decoration:underline;text-underline-offset:7px}.destination-editorial{display:grid;grid-template-columns:minmax(0,1fr) 300px;gap:70px;align-items:start}.destination-story{display:grid;gap:44px;min-width:0}.destination-aside{position:sticky;top:110px}.destination-planner{padding:27px;background:#f5f6f2;border:1px solid #e2e6df;border-radius:18px}.destination-planner>:global(svg){color:#9d853b;margin-bottom:20px}.destination-planner>.eyebrow{font-size:8px;color:#7d755a}.destination-planner h2{font-size:22px;font-weight:600;line-height:1.3;margin:16px 0}.location-line{display:flex;align-items:start;gap:8px;font-size:12px;line-height:1.8;color:#687b88}.location-line :global(svg){flex-shrink:0;margin-top:3px}.destination-scores{margin-top:25px;padding-top:20px;border-top:1px solid #dbe1df}.destination-scores>p{font-size:11px;color:#687b88;margin-bottom:17px}.destination-scores>div{display:grid;grid-template-columns:1fr auto;gap:7px;font-size:11px;margin-bottom:14px}.destination-scores meter{grid-column:1/-1;width:100%;height:7px}.map-link{display:flex;gap:8px;align-items:center;font-size:12px;margin-top:24px;text-decoration:underline;text-underline-offset:4px}.all-places{display:block;text-align:center;font-size:11px;margin-top:20px;color:#687b88}.destination-activity{border:1px solid #e0e5e6;border-radius:16px;overflow:hidden;background:white}.activity-photo{height:210px}.destination-activity>div{padding:24px}.destination-activity h3{font-size:20px;font-weight:600;line-height:1.4}.destination-activity p{font-size:13px;line-height:1.8;color:#647586;display:-webkit-box;-webkit-box-orient:vertical;-webkit-line-clamp:4;line-clamp:4;overflow:hidden;margin:14px 0 22px}.detail-questions{display:grid;gap:50px;grid-template-columns:repeat(auto-fit,minmax(min(100%,350px),1fr))}@media(max-width:1023px){.destination-editorial{gap:35px;grid-template-columns:minmax(0,1fr) 260px}}@media(max-width:767px){.destination-editorial{grid-template-columns:minmax(0,1fr)}.destination-aside{position:static}.destination-planner{padding:24px}.destination-section-nav>div{gap:24px}}
</style>
