-- The frontend accesses data through Express using the server service-role key.
-- Supabase grants anon/authenticated table access by default; RLS without client
-- policies keeps admin credentials, bookings and private messages backend-only.
-- service_role has BYPASSRLS and retains the API's existing read/write behavior.
-- Limit this migration to this application's tables, not unrelated public tables.
do $$
declare
  app_table text;
begin
  foreach app_table in array array[
    'accommodation_experiences',
    'accommodation_suppliers',
    'activities',
    'admin_users',
    'ai_answer_cache',
    'ai_conversations',
    'ai_eval_runs',
    'ai_lead_context',
    'ai_messages',
    'ai_tool_calls',
    'ai_usage_logs',
    'amenities',
    'analytics_events',
    'analytics_sessions',
    'audit_logs',
    'available_dates',
    'blog_categories',
    'blog_posts',
    'booking_amendments',
    'booking_payments',
    'booking_requests',
    'cms_embeddings',
    'comparisons',
    'connect_webhook_events',
    'contact_messages',
    'content_translations',
    'conversation_notes',
    'countries',
    'destinations',
    'error_logs',
    'exchange_rate_locks',
    'exchange_rate_snapshots',
    'faqs',
    'gallery_images',
    'homepage_sections',
    'hubspot_sync_logs',
    'itinerary_days',
    'languages',
    'lodge_alternatives',
    'lodge_amenities',
    'lodge_destinations',
    'lodge_experiences',
    'lodge_highlights',
    'lodge_images',
    'lodge_inclusions',
    'lodge_room_images',
    'lodge_rooms',
    'lodge_seasonal_rates',
    'lodge_suppliers',
    'lodge_tours',
    'lodges',
    'login_rate_limits',
    'media_library',
    'notification_events',
    'page_seo',
    'payment_requests',
    'permissions',
    'quotation_comments',
    'quotation_revisions',
    'quotations',
    'reviews',
    'role_permissions',
    'safari_packages',
    'safety_topics',
    'serengeti_migration_calendar',
    'slug_redirects',
    'specialists',
    'testimonials',
    'tour_categories',
    'tour_destinations',
    'tour_exclusions',
    'tour_group_prices',
    'tour_images',
    'tour_inclusions',
    'tour_match_results',
    'tour_price_options',
    'tour_pricing_seasons',
    'tours',
    'travel_styles',
    'trip_access_tokens',
    'trip_points',
    'website_settings',
    'whatsapp_accounts',
    'whatsapp_contacts',
    'whatsapp_messages',
    'whatsapp_templates',
    'whatsapp_webhook_events'
  ] loop
    execute format('alter table public.%I enable row level security', app_table);
  end loop;
end;
$$;

notify pgrst, 'reload schema';
