import { z } from 'zod';
const emptyToNull=(value:unknown)=>value===''||value===undefined?null:value;
const nullableNumber=z.preprocess(emptyToNull,z.coerce.number().nonnegative().nullable()).optional();
const uuidList=z.array(z.string().uuid()).max(250).default([]);
const image=z.object({image_url:z.string().min(1).max(2048),alt_text:z.string().max(300).optional().nullable(),caption:z.string().max(500).optional().nullable()});
export const lodgeDetailsReplaceSchema=z.object({
  highlights:z.array(z.object({title:z.string().min(1).max(180)})).max(30).default([]),
  rooms:z.array(z.object({name:z.string().min(1).max(160),room_type:z.enum(['STANDARD_ROOM','DELUXE_ROOM','SUPERIOR_ROOM','SUITE','FAMILY_ROOM','FAMILY_SUITE','SAFARI_TENT','LUXURY_TENT','COTTAGE','CHALET','VILLA','BUNGALOW','HONEYMOON_SUITE']),short_description:z.string().max(800).optional().nullable(),max_adults:z.coerce.number().int().min(0).max(30).optional().nullable(),max_children:z.coerce.number().int().min(0).max(30).optional().nullable(),max_guests:z.coerce.number().int().min(1).max(50).optional().nullable(),bed_types:z.array(z.enum(['SINGLE','TWIN','DOUBLE','QUEEN','KING','BUNK_BED','SOFA_BED','EXTRA_BED'])).max(8).default([]),unit_count:z.coerce.number().int().min(1).max(1000).optional().nullable(),views:z.array(z.enum(['GARDEN','POOL','MOUNTAIN','OCEAN','BEACH','RIVER','LAKE','SAVANNAH','FOREST','WILDLIFE','CITY','COURTYARD'])).max(12).default([]),amenities:z.array(z.string().max(80)).max(50).default([]),images:z.array(image).max(30).default([])})).max(50).default([]),
  rates:z.array(z.object({season_type:z.enum(['LOW_SEASON','GREEN_SEASON','SHOULDER_SEASON','HIGH_SEASON','PEAK_SEASON','FESTIVE_SEASON']),season_name:z.string().max(120).optional().nullable(),valid_from:z.string().date(),valid_until:z.string().date(),currency:z.string().length(3),rack_rate:nullableNumber,net_rate:nullableNumber,single_rate:nullableNumber,double_rate:nullableNumber,triple_rate:nullableNumber,child_rate:nullableNumber,single_supplement:nullableNumber,pricing_basis:z.enum(['PER_PERSON','PER_PERSON_SHARING','PER_ROOM','PER_UNIT','PER_NIGHT']),meal_plan:z.enum(['ROOM_ONLY','BED_AND_BREAKFAST','HALF_BOARD','FULL_BOARD','ALL_INCLUSIVE','FULL_BOARD_PLUS_ACTIVITIES']),notes:z.string().max(800).optional().nullable()})).max(100).default([]),
  inclusions:z.array(z.object({title:z.string().min(1).max(240),is_included:z.boolean()})).max(100).default([]),
  destination_ids:uuidList,tour_ids:uuidList,alternative_ids:uuidList,experience_ids:uuidList,
  supplier:z.object({supplier_id:z.union([z.string().uuid(),z.literal('')]).optional().nullable(),new_supplier_name:z.string().max(200).optional().nullable(),contact_person:z.string().max(160).optional().nullable(),reservation_email:z.union([z.string().email(),z.literal('')]).optional().nullable(),phone_whatsapp:z.string().max(80).optional().nullable(),commission_percent:z.coerce.number().min(0).max(100).optional().nullable(),contract_start:z.union([z.string().date(),z.literal('')]).optional().nullable(),contract_end:z.union([z.string().date(),z.literal('')]).optional().nullable(),payment_terms:z.string().max(3000).optional().nullable(),cancellation_terms:z.string().max(5000).optional().nullable(),supplier_preference:z.enum(['PREFERRED','STANDARD','BACKUP','DO_NOT_USE']).optional(),preferred_supplier:z.boolean().optional(),personally_inspected:z.boolean().optional(),last_inspection_date:z.union([z.string().date(),z.literal('')]).optional().nullable(),internal_notes:z.string().max(10000).optional().nullable(),contract_document_url:z.union([z.string().url(),z.literal('')]).optional().nullable()}).optional().nullable()
});
